'use client'

import { FormEvent, useMemo, useState } from "react";
import { ArrowRight, ChevronLeft, ChevronRight, Flame, Leaf, Menu, Search, Sparkles, UtensilsCrossed, X } from "lucide-react";

type MenuItem = { id:number; name:string; category:string; description:string; price:number; ingredients:string; dietary:string; portion:string; pairing:string };
const categories = ["All", "Tacos", "Burritos", "Drinks", "Desserts", "Appetizers", "Family Meals"];
const testimonials = [
  ["The tacos here are incredible. I drive across town just for the al pastor. Everything tastes like it was made this morning because it was.","Roberto C.","Local Regular","RC"],
  ["First time trying authentic Mexican food and I am hooked. The staff explained every dish and the flavors are phenomenal.","Sarah M.","Food Blogger","SM"],
  ["Best margaritas and burritos I have had outside of Mexico City. This place is a gem.","Diego L.","Food Critic","DL"],
];

export default function Marisol({ initialItems }: { initialItems: MenuItem[] }) {
  const [open,setOpen] = useState(false), [category,setCategory] = useState("All"), [query,setQuery] = useState("");
  const [selected,setSelected] = useState<MenuItem|null>(null), [quote,setQuote] = useState(0);
  const [form,setForm] = useState({name:"",email:"",message:""}), [status,setStatus] = useState<"idle"|"loading"|"success"|"error">("idle");
  const items = useMemo(() => initialItems.filter(i => (category === "All" || i.category === category) && `${i.name} ${i.description} ${i.ingredients}`.toLowerCase().includes(query.toLowerCase())),[initialItems,category,query]);
  async function submit(e:FormEvent) { e.preventDefault(); setStatus("loading"); try { const res=await fetch(`${process.env.NEXT_PUBLIC_CONSTRUCTOR_API}/v1/forms/${process.env.NEXT_PUBLIC_PROJECT_ID}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}); if(!res.ok) throw new Error(); setStatus("success"); } catch { setStatus("error"); } }
  const links = [["Our Story","story"],["Menu","menu"],["Gather","contact"]];
  return <main className="overflow-hidden bg-cream">
    <nav className="sticky top-0 z-40 border-b border-charcoal/10 bg-cream/95 backdrop-blur">
      <div className="mx-auto flex h-18 max-w-7xl items-center justify-between px-5 lg:px-8">
        <a href="#top" className="font-display text-3xl font-bold tracking-tight text-charcoal">Mari<span className="text-orange">sol</span></a>
        <div className="hidden items-center gap-8 md:flex">{links.map(([label,id])=><a key={id} href={`#${id}`} className="text-sm font-semibold hover:text-orange">{label}</a>)}<a href="#menu" className="rounded-full bg-orange px-5 py-3 text-sm font-bold text-white hover:bg-teal">Explore the menu</a></div>
        <button onClick={()=>setOpen(!open)} aria-label="Toggle navigation" aria-expanded={open} className="rounded-full border border-charcoal/20 p-2 md:hidden">{open?<X/>:<Menu/>}</button>
      </div>
      <div className={`absolute left-0 top-full w-full border-b border-charcoal/10 bg-cream px-5 py-5 shadow-xl transition-all duration-500 ease-[cubic-bezier(0.16,1,0.3,1)] md:hidden ${open?'translate-y-0 opacity-100 pointer-events-auto':'-translate-y-4 opacity-0 pointer-events-none'}`}>{links.map(([label,id],index)=><a key={id} href={`#${id}`} onClick={()=>setOpen(false)} style={{transitionDelay:open?`${index*60}ms`:'0ms'}} className="block border-b border-charcoal/10 py-4 font-display text-2xl transition-all duration-500">{label}</a>)}</div>
    </nav>

    <section id="top" className="grid min-h-[calc(100vh-72px)] lg:grid-cols-[56%_44%]">
      <div className="paper flex items-center px-6 py-20 sm:px-12 lg:px-[max(3rem,calc((100vw-80rem)/2))]">
        <div className="max-w-3xl"><div className="mb-8 flex items-center gap-3 text-xs font-bold uppercase tracking-[.24em] text-orange"><span className="h-px w-10 bg-orange"/>Fresh from the comal</div>
          <h1 className="font-display text-5xl font-bold leading-[.98] tracking-tight sm:text-7xl xl:text-[5.7rem]">Authentic Mexican flavors, <em className="font-normal text-orange">made fresh daily.</em></h1>
          <p className="mt-7 max-w-xl text-lg leading-8 text-stone">From traditional street tacos to house made agua fresca, explore our menu crafted by Chef María.</p>
          <div className="mt-9 flex flex-wrap gap-4"><a href="#menu" className="inline-flex items-center gap-3 rounded-full bg-orange px-7 py-4 font-bold text-white hover:bg-teal">View full menu <ArrowRight size={18}/></a><a href="#contact" className="rounded-full border border-charcoal px-7 py-4 font-bold hover:bg-charcoal hover:text-white">Plan your visit</a></div>
        </div>
      </div>
      <div role="img" aria-label="Artistic overhead composition of tacos on a clay plate" className="clay-art relative min-h-[480px] overflow-hidden lg:min-h-full"><div className="absolute left-8 top-8 rounded-full bg-cream/90 px-4 py-2 text-xs font-bold uppercase tracking-widest">Hecho con corazón</div><div className="absolute bottom-8 right-8 max-w-52 border-l-2 border-orange bg-charcoal/90 p-5 text-sm leading-6 text-white">Corn tortillas pressed each morning. Salsas ground in small batches.</div></div>
    </section>

    <div className="border-y border-charcoal/10 bg-sand"><div className="mx-auto flex max-w-7xl gap-8 overflow-x-auto px-6 py-5 text-xs font-bold uppercase tracking-wider [scrollbar-width:none]">{["15+ Years Serving the Community","100% Fresh Ingredients Daily","3,400+ Happy Customers Monthly","8 Signature House Recipes","Locally Sourced Produce"].map(x=><span key={x} className="flex shrink-0 items-center gap-3"><Sparkles size={14} className="text-orange"/>{x}</span>)}</div></div>

    <section id="story" className="mx-auto grid max-w-7xl gap-12 px-6 py-24 lg:grid-cols-2 lg:items-center lg:py-32">
      <div className="relative min-h-96"><div className="food-two absolute inset-y-0 left-0 w-[78%] rounded-[2rem]"/><div className="absolute bottom-0 right-0 w-56 rounded-tl-[3rem] bg-orange p-8 text-white"><Flame className="mb-8"/><p className="font-display text-2xl leading-tight">Fire, masa, and a little patience.</p></div></div>
      <div className="lg:pl-12"><p className="mb-4 text-xs font-bold uppercase tracking-[.25em] text-orange">Our kitchen</p><h2 className="font-display text-4xl font-bold leading-tight sm:text-5xl">Rooted in tradition.<br/>Brightened by Marisol.</h2><p className="mt-7 text-lg leading-8 text-stone">We cook the way a generous table should feel: lively, abundant, and made for sharing. Every plate begins with honest ingredients, warm tortillas, and recipes refined over years of community dinners.</p><div className="mt-9 grid grid-cols-2 gap-4"><div className="border-t border-charcoal pt-4"><Leaf className="text-orange"/><p className="mt-3 font-bold">Produce led</p><p className="text-sm text-stone">Seasonal vegetables and bright herbs</p></div><div className="border-t border-charcoal pt-4"><UtensilsCrossed className="text-orange"/><p className="mt-3 font-bold">Made each day</p><p className="text-sm text-stone">Salsas, marinades, and masa</p></div></div></div>
    </section>

    <section id="menu" className="bg-charcoal px-5 py-24 text-cream lg:py-32"><div className="mx-auto max-w-7xl">
      <div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><p className="mb-4 text-xs font-bold uppercase tracking-[.25em] text-orange">Come hungry</p><h2 className="font-display text-5xl font-bold sm:text-6xl">The Marisol menu</h2></div><label className="flex max-w-md items-center gap-3 rounded-full border border-cream/20 px-5 py-3"><Search size={18}/><span className="sr-only">Search the menu</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search dishes or ingredients" className="w-full bg-transparent text-sm placeholder:text-cream/50 focus:outline-none"/></label></div>
      <div className="mt-10 flex gap-2 overflow-x-auto pb-3 [scrollbar-width:none]">{categories.map(c=><button key={c} onClick={()=>setCategory(c)} className={`shrink-0 rounded-full px-5 py-2.5 text-sm font-bold transition ${category===c?'bg-orange text-white':'border border-cream/20 hover:border-orange hover:text-orange'}`}>{c}</button>)}</div>
      {items.length ? <div className="mt-10 grid gap-x-12 lg:grid-cols-2">{items.map((item,index)=><article key={item.id} className="group flex gap-5 border-t border-cream/15 py-7"><div className={`h-24 w-24 shrink-0 rounded-full ${index%3===0?'food-one':index%3===1?'food-two':'food-three'}`}/><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-4"><h3 className="font-display text-xl font-bold">{item.name}</h3><span className="font-bold text-orange">${item.price.toFixed(2)}</span></div><p className="mt-2 text-sm leading-6 text-cream/65">{item.description}</p><button onClick={()=>setSelected(item)} className="mt-3 text-xs font-bold uppercase tracking-widest text-orange hover:text-white">View details <span aria-hidden>→</span></button></div></article>)}</div>:<p className="py-20 text-center text-cream/60">No dishes match your search. Try another flavor.</p>}
    </div></section>

    <section className="px-6 py-24 lg:py-32"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.25em] text-orange">A table for every appetite</p><h2 className="mt-4 font-display text-4xl font-bold sm:text-5xl">Choose your kind of feast</h2></div><div className="mt-12 grid border-y border-charcoal/15 lg:grid-cols-3">{[["01","Street Snacks","$2.95 to $5.75","A quick bite","Tacos and appetizers","Pair with agua fresca"],["02","Combo Plates","$9.95 to $13.95","One generous plate","Burrito, rice, and beans","Pair with a michelada"],["03","Family Feasts","$24.95 to $42.95","Serves four to six","Mixed tacos, salsas, and sides","Aguas frescas included"]].map((t,i)=><div key={t[1]} className={`py-10 lg:px-9 ${i>0?'border-t border-charcoal/15 lg:border-l lg:border-t-0':''}`}><span className="font-display text-5xl text-orange/30">{t[0]}</span><h3 className="mt-8 font-display text-3xl font-bold">{t[1]}</h3><p className="mt-2 font-bold text-orange">{t[2]}</p><ul className="mt-7 space-y-3 text-sm text-stone">{t.slice(3).map(x=><li key={x} className="flex gap-3"><span className="text-orange">✦</span>{x}</li>)}</ul></div>)}</div></div></section>

    <section className="grid min-h-[650px] grid-cols-2 grid-rows-2 md:grid-cols-4"><div className="food-one col-span-2 row-span-2 flex items-end p-8"><p className="max-w-xs font-display text-4xl text-white">Color on every plate</p></div><div className="food-two p-5"><span className="rounded-full bg-cream px-3 py-1 text-xs font-bold">Slow cooked</span></div><div className="bg-teal p-8 text-cream"><p className="font-display text-3xl">Made to share</p></div><div className="bg-orange p-8 text-white"><p className="text-xs font-bold uppercase tracking-widest">Every day</p><p className="mt-3 font-display text-3xl">Fresh masa</p></div><div className="food-three"/></section>

    <section className="bg-sand px-6 py-24"><div className="mx-auto max-w-5xl text-center"><p className="text-xs font-bold uppercase tracking-[.25em] text-orange">From our table</p><div className="mt-10 text-5xl text-orange">“</div><blockquote className="mx-auto max-w-4xl font-display text-3xl leading-snug sm:text-4xl">{testimonials[quote][0]}</blockquote><div className="mt-8 flex items-center justify-center gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-full bg-teal font-bold text-white">{testimonials[quote][3]}</div><div className="text-left"><p className="font-bold">{testimonials[quote][1]}</p><p className="text-sm text-stone">{testimonials[quote][2]}</p></div></div><div className="mt-10 flex justify-center gap-3"><button aria-label="Previous testimonial" onClick={()=>setQuote((quote+2)%3)} className="rounded-full border border-charcoal/30 p-3 hover:bg-charcoal hover:text-white"><ChevronLeft/></button><button aria-label="Next testimonial" onClick={()=>setQuote((quote+1)%3)} className="rounded-full border border-charcoal/30 p-3 hover:bg-charcoal hover:text-white"><ChevronRight/></button></div></div></section>

    <section className="bg-orange px-6 py-24 text-center text-white"><p className="text-xs font-bold uppercase tracking-[.25em]">Your table is waiting</p><h2 className="mx-auto mt-5 max-w-4xl font-display text-5xl font-bold leading-tight sm:text-7xl">Come for the tacos.<br/>Stay for the sobremesa.</h2><a href="#contact" className="mt-10 inline-flex items-center gap-3 rounded-full bg-cream px-7 py-4 font-bold text-charcoal hover:bg-teal hover:text-white">Get in touch <ArrowRight size={18}/></a></section>

    <section id="contact" className="grid lg:grid-cols-2"><div className="paper px-6 py-24 lg:px-16"><div className="mx-auto max-w-xl"><p className="text-xs font-bold uppercase tracking-[.25em] text-orange">Visit Marisol</p><h2 className="mt-4 font-display text-5xl font-bold">Let us set the table.</h2><p className="mt-6 leading-7 text-stone">Planning a group meal, asking about ingredients, or arranging pickup? Send a note and our team will help.</p><div className="mt-12 border-l-2 border-orange pl-6"><p className="font-display text-2xl">Dine in · Pickup · Delivery</p><p className="mt-2 text-sm text-stone">Availability may vary by day.</p></div></div></div><div className="bg-teal px-6 py-24 text-white lg:px-16"><div className="mx-auto max-w-xl">{status==="success"?<div role="status" className="rounded-2xl border border-white/20 p-8 text-xl">✓ Mensaje enviado — te contactaremos pronto</div>:<form onSubmit={submit} className="space-y-6"><label className="block text-sm font-bold">Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="mt-2 w-full border-b border-white/40 bg-transparent py-3 font-normal focus:outline-none"/></label><label className="block text-sm font-bold">Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} className="mt-2 w-full border-b border-white/40 bg-transparent py-3 font-normal focus:outline-none"/></label><label className="block text-sm font-bold">How can we help?<textarea required rows={4} value={form.message} onChange={e=>setForm({...form,message:e.target.value})} className="mt-2 w-full resize-none border-b border-white/40 bg-transparent py-3 font-normal focus:outline-none"/></label>{status==="error"&&<p role="alert" className="rounded bg-white/10 p-3">We could not send your message. Please try again.</p>}<button disabled={status==="loading"} className="inline-flex rounded-full bg-orange px-7 py-4 font-bold text-white hover:bg-cream hover:text-charcoal disabled:opacity-60">{status==="loading"?"Enviando…":"Send message"}</button></form>}</div></div></section>

    <footer className="bg-charcoal px-6 py-14 text-cream"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-9 md:flex-row md:items-end"><div><p className="font-display text-4xl font-bold">Mari<span className="text-orange">sol</span></p><p className="mt-3 text-sm text-cream/55">Modern Mexican cooking. Made fresh, served warmly.</p></div><div className="flex flex-wrap gap-6 text-sm">{links.map(([label,id])=><a key={id} href={`#${id}`} className="hover:text-orange">{label}</a>)}</div><p className="text-xs text-cream/45">© 2026 Marisol</p></div></footer>

    {selected&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-charcoal/70 p-4 sm:items-center" role="dialog" aria-modal="true" aria-labelledby="dish-title" onMouseDown={e=>{if(e.currentTarget===e.target)setSelected(null)}}><div className="w-full max-w-lg rounded-3xl bg-cream p-7 shadow-2xl"><div className="flex justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-orange">{selected.category}</p><h2 id="dish-title" className="mt-2 font-display text-3xl font-bold">{selected.name}</h2></div><button aria-label="Close dish details" onClick={()=>setSelected(null)} className="h-10 rounded-full border border-charcoal/20 p-2"><X/></button></div><p className="mt-5 leading-7 text-stone">{selected.description}</p><dl className="mt-7 grid grid-cols-2 gap-4 border-y border-charcoal/15 py-6 text-sm"><div><dt className="font-bold">Ingredients</dt><dd className="mt-1 text-stone">{selected.ingredients}</dd></div><div><dt className="font-bold">Dietary note</dt><dd className="mt-1 text-stone">{selected.dietary}</dd></div><div><dt className="font-bold">Portion</dt><dd className="mt-1 text-stone">{selected.portion}</dd></div><div><dt className="font-bold">Pairs with</dt><dd className="mt-1 text-stone">{selected.pairing}</dd></div></dl><div className="mt-6 flex items-center justify-between"><span className="font-display text-3xl font-bold text-orange">${selected.price.toFixed(2)}</span><button onClick={()=>setSelected(null)} className="rounded-full bg-charcoal px-6 py-3 font-bold text-white hover:bg-teal">Back to menu</button></div></div></div>}
  </main>
}
